spring:
    datasource:
        url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=true
        username: root
        password: sahil007

    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

# #The SQL dialect makes Hibernate generate better SQL for the chosen database
#     jpa:
#         properties:
#             hibernate:
#                 dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#JPA Settings
    jpa.hibernate.ddl_auto: create

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs   # You can customize this path
  swagger-ui:
    enabled: true
    path: /swagger-ui    # Accessible at /swagger-ui/index.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json